#!/usr/bin/python

BoysNames = [ "Aaron", "Adam", "Alexander", "Andrew", "Anthony", "Austin",
              "Benjamin", "Blake", "Brandon", "Brendan", "Brian", "Brady",
              "Bryson", "Charles", "Christian", "Christopher", "Cody", "Conner",
              "Daniel", "Dean", "Derek", "Donald", "Dylan", "Edward", "Eli",
              "Eric", "Ethan", "Evan", "Felix", "Ferris", "Floyd", "Flynn",
              "Foster", "Frederick", "Garrett", "Gavin", "Gerald", "Glenn",
              "Gordon", "Grant", "Gregory", "Hal", "Hans", "Harold", "Hayden",
              "Henry", "Howard", "Hugh", "Ian", "Ignatius", "Isaac", "Isaiah",
              "Ishmael", "Jacob", "James", "Jason", "Jeremy", "John",
              "Jonathan", "Joseph", "Joshua", "Justin", "Keith", "Kenneth",
              "Kevin", "Kirk", "Kurt", "Kyle", "Lawrence", "Leonard", "Logan",
              "Louis", "Luke", "Mason", "Matthew", "Maxwell", "Merritt",
              "Michael", "Milton", "Morgan", "Nathan", "Newman", "Nicholas",
              "Nigel", "Noah", "Norman", "Olin", "Omar", "Orson", "Oswald",
              "Otto", "Owen", "Parker", "Patrick", "Paul", "Perry", "Philip",
              "Pierce", "Preston", "Quentin", "Quincy", "Quinn", "Richard",
              "Riley", "Robert", "Ryan", "Roland", "Roy", "Ruben", "Samuel",
              "Sander", "Sawyer", "Scott", "Sean", "Sheldon", "Spencer",
              "Steven", "Thomas", "Theodore", "Timothy", "Trenton", "Trevor",
              "Troy", "Tucker", "Tyler", "Val", "Vaughn", "Vernon", "Victor",
              "Vincent", "Virgil", "Wade", "Warren", "Wesley", "Wilbur",
              "Wilfred", "William", "Wilson", "Wyatt", "Xander", "Xavier",
              "Yancy", "Yves", "Yuri", "Zachary", "Zane", "Zebulon" ]

GirlsNames = ["Abaigeal", "Abana", "Abbey", "Abbie", "Abby", "Abegaila",
              "Abelia", "Abi", "Abigail", "Abilene", "Acacia", "Ada", "Addie",
              "Aesha", "Agatha", "Aideen", "Aimee", "Ainsley", "Ailsa", "Aisha",
              "Alaina", "Alana", "Alanah", "Alberta", "Alcinda", "Aleida",
              "Alena", "Alesa", "Alessia", "Aletia", "Alexa", "Alexandra",
              "Alicia", "Alida", "Alina", "Alisha", "Alissa", "Allie",
              "Allison", "Alma", "Althea", "Alysen", "Alyssa", "Amanda",
              "Amber", "Amberlee", "Ambrosia", "Amelia", "Amethyst", "Amiela",
              "Amy", "AnaMaree", "Anastasia", "Andie", "Andra", "Andrea",
              "Andriana", "Anesa", "Angel", "Angela", "Angelica", "Angelika",
              "Angelina", "Angie", "Ann", "Anna", "Annabeth", "Annalee",
              "Annaliese", "Annalisa", "Annette", "Annie", "Annitta", "Antheia",
              "Antonella", "Arabella", "Arianne", "Ariel", "Arlene", "Aubrey",
              "Aubry", "Augusta", "Avis.", "Beatrice", "Beatrix", "Becca",
              "Belinda", "Belle", "Benita", "Bernadette", "Bernice", "Bernita",
              "Berta", "Beryl", "Bess", "Bessie", "Beta", "Beth", "Betsy",
              "Betty", "Bev", "Beverly", "Bianca", "Billie", "Billy", "Blossom",
              "Bridget", "Bridgid", "Brigit", "Brigitte", "Britney", "Brittany",
              "Brooke", "Brooklyn", "Bryana", "Caitriona", "Calandra", "Callie",
              "Camelia", "Camella", "Camila", "Camilla", "Camillah", "Cammie",
              "Candice", "Candee", "Candi", "Candis", "Candy", "Caprice",
              "Cara", "Caresse", "Carey", "Cari", "Carina", "Carine", "Carisa",
              "Carla", "Carlana", "Carlee", "Carlene", "Carley", "Carlie",
              "Carmel", "Carmella", "Carmen", "Carmencita", "Carol", "Carolina",
              "Catalina", "Cate", "Cath", "Cathie", "Cathleen", "Cathlin",
              "Cecily", "Celia", "Celine", "Celeste", "Celestina", "Celestine",
              "Celestyn", "Chandelle", "Chanel", "Chantal", "Charleen",
              "Charlene", "Charlie", "Charlot", "Charlotte", "Charly",
              "Charmain", "Charmaine", "Chase", "Chelsea", "Chelsey",
              "Cherry", "Cheryl", "Cheryll", "Chrissie", "Chrissy", "Christa",
              "Christabel", "Christal", "Christel", "Christelle", "Christiane",
              "Christie", "Christin", "Christina", "Christine", "Clarabelle",
              "Clare", "Clarisa", "Clarissa", "Claudette", "Claudia",
              "Claudine", "Colene", "Colette", "Collana", "Constance",
              "Coral", "Coreen", "Corina", "Corine", "Cory", "Courtney",
              "Crissie", "Crissy", "Cristina", "Crystal", "Cybil", "Cybill",
              "Dahlia", "Daisy", "Dale", "Dana", "Danette", "Dani", "Daniela",
              "Dannah", "Daphne", "Darcee", "Darcy", "Darcy", "Dawn", "Deanna",
              "Delwyn", "Delyth", "Demi", "Dena", "Denell", "Denise", "Desiree",
              "Diana", "Diane", "Dianna", "Dianne", "Diantha", "Dina", "Dinah",
              "Dolores", "Dominique", "Donatella", "Donella", "Donna", "Dora",
              "Doreen", "Dorothy", "Drew", "Ebony", "Eden", "Edna", "Edwina",
              "Eileen", "Elaine", "Eleanor", "Eli", "Elisa", "Elisabeth",
              "Elissa", "Eliza", "Elizabeth", "Ella", "Ellen", "Elli",
              "Ellie", "Ellinor", "Elly", "Elma", "Eloise", "Emilie", "Emily",
              "Emma", "Enid", "Erica", "Erika", "Erin", "Erina", "Eryn",
              "Esmeralda", "Estella", "Estelle", "Ester", "Euna", "Eunice",
              "Eve", "Eveleen", "Fae", "Faith", "Farrah", "Fay", "Faye",
              "Felicia", "Felicity", "Fern", "Fifi", "Fleur", "Floella",
              "Flora", "Florence", "Florens", "Florenz", "Fran", "Franca",
              "Frances", "Francesca", "Gabriela", "Gabriell", "Gabriella",
              "Gabrielle", "Gail", "Gayle", "Gemma", "Geneva", "Genevieve",
              "Georgette", "Georgia", "Georgie", "Georgina", "Geraldine",
              "Gertrud", "Gillian", "Giselle", "Gladys", "Glenda", "Glenys",
              "Gloria", "Gloriana", "Glynn", "Goloria", "Goldie", "Grace",
              "Gracie", "Greta", "Gretchen", "Gretel", "Gwen", "Gwyneth.",
              "Halley", "Hallie", "Harriet", "Hayley", "Heather", "Heidi",
              "Helaine", "Helana", "Helen", "Helena", "Helene", "Henrietta",
              "Hilary", "Hilda", "Hillary", "Holly", "Hope", "Hyacinth", "Ida",
              "Imogen", "Iona", "Ingrid", "Irena", "Irene", "Irina", "Iris",
              "Jacalyn", "Jacaranda", "Jacinda", "Jacinta", "Jackie",
              "Jacqueline", "Jacqui", "Jacynth", "Jade", "Jaime", "Jaleen",
              "Jamie", "Jan", "Janae", "Jane", "Janel", "Janessa", "Janet",
              "Janey", "Janice", "Janie", "Janis", "Janita", "Jasmin",
              "Jasmine", "Jaylene", "Jayme", "Jayne", "Jazmin", "Jean",
              "Jeana", "Jessa", "Jessi", "Jessica", "Jessie", "Jessy", "Jill",
              "Jillian", "Jinny", "Jo", "Joan", "Joanna", "Joceline", "Jocelyn",
              "Jo Ella", "Jodi", "Jodie", "Jody", "Johana", "Johanna",
              "Jolanda", "Joleen", "Jordan", "Josephine", "Josie", "Joss",
              "Joy", "Joyce", "Jude", "Judith", "Judy", "Juli", "Julia",
              "Julie", "Julienne", "Juliet", "June", "Kaitlin", "Kala",
              "Kalani", "Kalee", "Kali", "Kallie", "Kami", "Kara", "Karen",
              "Karena", "Kari", "Karin", "Karina", "Karissa", "Karla",
              "Karren", "Kasa", "Kasi", "Kate", "Katelin", "Kath", "Katharina",
              "Kathe", "Katherine", "Kathi", "Kathie", "Kathleen", "Kathryn",
              "Katie", "Katrina", "Katy", "Katya", "Kayla", "Kaylie", "Kaylenn",
              "Kayley", "Kaylynn", "Keisha", "Kelly", "Kelsey", "Kelsi",
              "Kessa", "Kiley", "Kim", "Kimberlee", "Kimberley", "Kimberly",
              "Kira", "Kiri", "Kirsten", "Kirsti", "Kirstin", "Kitty",
              "Klarissa", "Klarysa", "Klaudia", "Krislyn", "Krissy", "Krista",
              "Kristal", "Kristen", "Kristie", "Kristin", "Kristina", "Kristy",
              "Kristin", "Kyla", "Kylie", "Lacy", "Lana", "Lara", "Larisa",
              "Laura", "Laureen", "Lauren", "Leah", "Leanne", "Lee", "Leigh",
              "Leila", "Leisha", "Lenice", "Lesley", "Leticia", "Lexa", "Lexi",
              "Lexy", "Liana", "Liane", "Libby", "Licia", "Lila", "Lili",
              "Lilian", "Lilly", "Linda", "Lindsay", "Lisa", "Loreen",
              "Loretta", "Lorinda", "Lorna", "Lorraine", "Lottie", "Louisa",
              "Louise", "Lucerne", "Lucia", "Lucinda", "Lucy", "Lydia",
              "Lynda", "Lynette", "Madeleine", "Madeline", "Madelyn", "Madge",
              "Madison", "Madonna", "Maegan", "Maeve", "Maggie", "Maisie",
              "Mallory", "Marica", "Margaret", "Marge", "Margie", "Margo",
              "Margot", "Maria", "Marian", "Marianne", "Marie", "Marien",
              "Marilyn", "Marisa", "Marissa", "Marjorie", "Martha", "Mary",
              "Matilda", "Maud", "Maude", "Maureen", "Mavis", "Maxine", "May",
              "Megan", "Meghan", "Melanie", "Melinda", "Melisa", "Melissa",
              "Melodie", "Melody", "Meredith", "Michelle", "Mildred", "Millie",
              "Mimi", "Mindy", "Miranda", "Miriam", "Molly", "Monica",
              "Monique", "Morgan", "Muriel", "Nadia", "Nadine", "Nadira",
              "Nancy", "Nanette", "Natalie", "Natasha", "Nelli", "Nellie",
              "Nelly", "Nichola", "Nichole", "Nickie", "Nicola", "Nikki",
              "Nikola", "Nina", "Nola", "Nora", "Norah", "Noreen",
              "Olive", "Olivia", "Paige", "Pam", "Pamela", "Patience",
              "Patrice", "Patricia", "Patsy", "Paula", "Paulette", "Paulina",
              "Pauline", "Peggy", "Peni", "Penny", "Pennington", "Petra",
              "Phebe", "Philippa", "Phillis", "Phoebe", "Phylicia", "Phyllis",
              "Pippa", "Polly", "Pollyam", "Pollyanna", "Poppy", "Portia",
              "Priscilla", "Prudence", "Rachael", "Rachel", "Rachelle",
              "Rae", "Raeleen", "Rai", "Rasheda", "Rashida", "Rayna", "Rea",
              "Reagan", "Reanna", "Rebecca", "Rebekah", "Rebekka", "Rei",
              "Rhea", "Rheanna", "Rhianna", "Rhoda", "Rhonda", "Ria",
              "Rickie", "Riley", "Rimona", "Rina", "Rita", "Roberta", "Robin",
              "Robyn", "Rochelle", "Romana", "Ros", "Rosanne", "Rosaleen",
              "Rosalia", "Rosalie", "Rosalind", "Rose", "Roseanne",  "Rosemary",
              "Rosie", "Roslyn", "Rowena", "Roxana", "Roxann", "Roxanne",
              "Ruby", "Sabrina", "Sadie", "Safia", "Salena", "Sally", "Salma",
              "Samantha", "Sandi", "Sandy", "Sandyha", "Sara", "Sarah",
              "Sarala", "Sasha", "Savina", "Scarlett", "Selena", "Selene",
              "Shannon", "Sharleen", "Sharlotte", "Sharon", "Sheela", "Sheena",
              "Shela", "Shelley", "Shellie", "Shelly", "Sherri", "Sherrie",
              "Sherry", "Shiela", "Shieryl", "Shiree", "Shirley", "Silvia",
              "Simone", "Sindy", "Sondra", "Sonja", "Sonya", "Sophia", "Sophie",
              "Sophy", "Stacey", "Staci", "Stacie", "Stefanie", "Stella",
              "Steph", "Stephanie", "Sue", "Suela", "Susan", "Susana",
              "Susannah", "Susie", "Suzanna", "Suzannah", "Suzanne", "Suzie",
              "Suzy", "Sybil", "Tabitha", "Talia", "Tam", "Tamara", "Tami",
              "Tammi", "Tammie", "Tammy", "Tania", "Tansy", "Tanya", "Taylor",
              "Teresa", "Terri", "Terry", "Tess", "Tessa", "Tessi", "Thea",
              "Thelma", "Theresa", "Tia", "Tina", "Toni", "Tori",
              "Tracey", "Traci", "Tracy", "Trish", "Trisha", "Trudie", "Trudy",
              "Una", "Val", "Valaree", "Valda", "Valeria", "Valerie", "Vanessa",
              "Velma", "Venessa", "Vera", "Veronica",  "Veronique", "Vicki",
              "Vickie", "Vicky", "Victoire", "Victoria", "Viki", "Virginia", "Viv",
              "Wendie", "Wendy", "Whitney", "Whoopi", "Wilma", "Winnifred",
              "Yasmin", "Yasmine", "Yolanda", "Yvette", "Zoe", ]

LastNames = [ "Abrahams", "Acker", "Ackerman", "Adamson", "Addison", "Adkins",
              "Aiken", "Aitken", "Akers", "Alberts", "Albinson", "Alexander",
              "Alfredson", "Alfson", "Allard", "Allsopp", "Alvey", "Anderson",
              "Andrews", "Andrewson", "Anson", "Anthonyson", "Appleby",
              "Appleton", "Archer", "Arkwright", "Armistead", "Arnold",
              "Arrington", "Arterberry", "Arterbury", "Arthur", "Arthurson",
              "Ash", "Ashley", "Ashworth", "Atkins", "Atkinson", "Attaway",
              "Atteberry", "Atterberry", "Attwater", "Augustine", "Auteberry",
              "Autenberry", "Auttenberg", "Avery", "Ayton", "Babcock",
              "Babcocke", "Babcoke", "Backus", "Badcock", "Badcocke",
              "Bagley", "Bailey", "Baker", "Baldwin", "Bancroft", "Banister",
              "Banks", "Barber", "Bardsley", "Barker", "Barlow", "Barnes",
              "Barton", "Bartram", "Bass", "Bates", "Bateson", "Battle",
              "Batts", "Baxter", "Beake", "Beasley", "Beattie", "Becket",
              "Beckett", "Beckham", "Belcher", "Bellamy", "Benbow",
              "Bennet", "Bennett", "Benson", "Benton", "Bernard", "Berry",
              "Bird", "Bishop", "Black", "Blackbourne", "Blackburn", "Blackman",
              "Blackwood", "Blake", "Blakeslee", "Bloodworth", "Bloxam",
              "Bloxham", "Blue", "Blythe", "Boivin", "Bolton", "Bond",
              "Bonham", "Bonher", "Bonner", "Bonney", "Boone", "Booner",
              "Boothman", "Botwright", "Bourke", "Boyce", "Braddock",
              "Bradford", "Bradley", "Brams", "Bramson", "Brasher",
              "Brassington", "Bray", "Breckenridge", "Breckinridge",
              "Brewer", "Brewster", "Brigham", "Bristol", "Bristow",
              "Britton", "Broadbent", "Brock", "Brooks", "Brown", "Brownlow",
              "Bryant", "Bryson", "Bullard", "Bulle", "Bullock", "Bunker",
              "Burke", "Burnham", "Burrell", "Burton", "Bush", "Butcher",
              "Butler", "Butts", "Byrd", "Cannon", "Cantrell", "Carl",
              "Carlisle", "Carlyle", "Carpenter", "Carter", "Cartwright",
              "Caulfield", "Causer", "Causey", "Chamberlain", "Chance",
              "Chancellor", "Chandler", "Chapman", "Chase", "Cheshire",
              "Christians", "Christianson", "Christinsen", "Christinson",
              "Christisen", "Christison", "Christopher", "Christophers",
              "Church", "Clark", "Clarke", "Clarkson", "Clausson", "Clawson",
              "Clayton", "Clemens", "Clifford", "Cline", "Clinton", "Close",
              "Coburn", "Collingwood", "Combs", "Comstock", "Constable", "Cook",
              "Cooke", "Cookson", "Coombs", "Cooper", "Corra", "Cotterill",
              "Cowden", "Cox", "Crawford", "Crewe", "Cristians", "Cristiansen",
              "Cristianson", "Croft", "Cropper", "Cross", "Crouch", "Cummins",
              "Curtis", "Dalton", "Danell", "Daniel", "Daniell", "Daniels",
              "Danielson", "Dannel", "Danniel", "Danniell", "Darby",
              "Davies", "Davis", "Davison", "Dawson", "Day", "Deadman",
              "Deering", "Denman", "Dennel", "Dennell", "Derrick", "Derricks",
              "Derrickson", "Dexter", "Dick", "Dickens", "Dickenson",
              "Dickson", "Disney", "Dixon", "Donalds", "Donaldson", "Downer",
              "Draper", "Duke", "Dukeson", "Durant", "Dwerryhouse", "Dyer",
              "Eads", "Earl", "Earls", "Earlson", "Easom", "Eason", "Eaton",
              "Eccleston", "Ecclestone", "Edison", "Edwards", "Edwardson",
              "Elder", "Eldridge", "Elliot", "Ellison", "Ellisson", "Elliston",
              "Ellsworth", "Elmerson", "Ely", "Emerson", "Endicott", "Ericson",
              "Espenson", "Ethans", "Ethanson", "Eustis", "Evanson", "Evered",
              "Fabian", "Fairbairn", "Fairburn", "Fairchild", "Fairclough",
              "Faulkner", "Fay", "Fear", "Fenn", "Firmin", "Fisher",
              "Fishman", "Fitzroy", "Fleming", "Fletcher", "Ford", "Forester",
              "Forney", "Foss", "Foster", "Fox", "Franklin", "Freeman", "Frost",
              "Fry", "Frye", "Fuller", "Gabriels", "Gabrielson", "Gardenar",
              "Gardiner", "Gardner", "Gardyner", "Garner", "Garrard", "Garrod",
              "Georgeson", "Gibb", "Gibbs", "Gibson", "Gilbert", "Giles", "Glendon",
              "Gilliam", "Glover", "Godfrey", "Goffe", "Goode", "Gorbold",
              "Gore", "Granger", "Grant", "Gray", "Green", "Greene",
              "Gregory", "Grey", "Groves", "Gully", "Hackett", "Hadaway",
              "Haden", "Haggard", "Haight", "Hale", "Hall", "Hallman",
              "Hameldon", "Hamilton", "Hamm", "Hampson", "Hampton", "Hancock",
              "Hanley", "Hanson", "Harden", "Hardwick", "Hardy", "Harford",
              "Hargrave", "Harley", "Harlow", "Harman", "Harmon", "Haroldson",
              "Harper", "Harrell", "Harrelson", "Harris", "Harrison", "Hart",
              "Hartell", "Harvey", "Hathaway", "Hatheway", "Hathoway", "Haward",
              "Hawk", "Hawking", "Hawkins", "Hayward", "Haywood", "Heath",
              "Henderson", "Hendry", "Henryson", "Henson", "Hepburn", "Herbert",
              "Herberts", "Herbertson", "Hermanson", "Hewitt", "Hext",
              "Hicks", "Hightower", "Hill", "Hillam", "Hilton", "Hobbes",
              "Hobbs", "Hobson", "Hodges", "Hodson", "Hogarth", "Hollands",
              "Hollins", "Holme", "Holmes", "Holmwood", "Holt", "Honeycutt",
              "Honeysett", "Hooker", "Hooper", "Hope", "Hopkins", "Hopper",
              "Hopson", "Horne", "Horsfall", "Horton", "House", "Howard",
              "Howe", "Howland", "Howse", "Huddleson", "Huddleston", "Hudnall",
              "Hudson", "Huff", "Hughes", "Hull", "Hume", "Hunnisett", "Hunt",
              "Hunter", "Hurst", "Hutson", "Huxley", "Huxtable", "Hyland",
              "I'Anson", "Ibbot", "Ibbott", "Ikin", "Ingham", "Ingram",
              "Jackson", "Jacobs", "Jacobson", "James", "Jamison", 
              "Janson", "Jardine", "Jarvis", "Jeffers", "Jefferson", "Jeffery",
              "Jeffries", "Jenkins", "Jephson", "Jepson", "Jernigan", "Jerome",
              "Jinks", "Johns", "Johnson", "Joiner", "Jones", "Josephs",
              "Josephson", "Joyner", "Keegan", "Keen", "Kellogg", "Kelsey",
              "Kemp", "Kendall", "Kendrick", "Kersey", "Kevins", "Kevinson",
              "Key", "Keys", "Kidd", "Killam", "Kimball", "King", "Kipling",
              "Kirby", "Kitchen", "Kitchens", "Knaggs", "Knight", "Law",
              "Lawson", "Leach", "Leavitt", "Ledford", "Leon", "Leonardson",
              "Levitt", "Lewis", "Linwood", "Little", "Lockwood", "Loman",
              "Long", "Longstaff", "Low", "Lowry", "Lucas", "Lukeson", "Lum",
              "Lund", "Lynn", "Lyon", "Maddison", "Madison", "Mallory",
              "Malone", "Mann", "Marchand", "Mark", "Marley", "Marlow",
              "Marsden", "Marshall", "Marston", "Martin", "Martins",
              "Martinson", "Mason", "Masters", "Masterson", "Mathers",
              "Mathews", "Mathewson", "Matthews", "Matthewson", "May", "Mayes",
              "Meadows", "Mercer", "Merchant", "Merrick", "Merricks",
              "Merritt", "Michaels", "Michaelson", "Midgley",
              "Milburn", "Miles", "Milford", "Miller", "Millhouse",
              "Mills", "Milton", "Mitchell", "Mondy", "Montgomery",
              "Moors", "Morce", "Morison", "Morris", "Morrish", "Morrison",
              "Morriss", "Morse", "Moses", "Mottershead", "Mounce",
              "Murgatroyd", "Murray", "Muttoone", "Myers", "Myles", "Nathans",
              "Nathanson", "Nelson", "Ness", "Neville", "Newell", "Newman",
              "Newport", "Newton", "Nichols", "Nicholson", "Nicolson",
              "Nielson", "Nigel", "Nixon", "Normanson", "North", "Northrop",
              "Norwood", "Nye", "Oakley", "Odell", "Ogden", "Olhouser",
              "Orman", "Osborne", "Osbourne", "Ott", "Outlaw", "Outterridge",
              "Overton", "Owston", "Padmore", "Page", "Palmer", "Parent",
              "Parker", "Parsons", "Paternoster", "Paterson", "Patrick",
              "Patterson", "Paulson", "Payne", "Peacock", "Peak", "Pearson",
              "Pelley", "Pemberton", "Penny", "Perkins", "Perry", "Peter",
              "Peters", "Peterson", "Petit", "Pettigrew", "Philips", "Phillips",
              "Pickering", "Pickle", "Pierson", "Pitts", "Plank", "Plaskett",
              "Platt", "Pocock", "Polley", "Pond", "Poole", "Pope", "Porcher",
              "Porter", "Potter", "Pound", "Powers", "Prescott", "Pressley",
              "Preston", "Proudfoot", "Pryor", "Purcell", "Putnam", "Queen",
              "Queshire", "Quick", "Quickley", "Quigg", "Quigley", "Quincey",
              "Quincy", "Raines", "Rains", "Rake", "Rakes", "Ramsey", "Randall",
              "Rayne", "Raynerson", "Readdie", "Reed", "Reeve",
              "Reier", "Rennell", "Rennold", "Rennoll", "Revie", "Reynell",
              "Reynolds", "Rice", "Richard", "Richards", "Richardson",
              "Rider", "Ridley", "Rier", "Rigby", "Riley", "Rimmer", "Roach",
              "Robbins", "Robert", "Roberts", "Robertson", "Robinson",
              "Rogers", "Rogerson", "Rollins", "Romilly", "Roscoe", "Ross",
              "Rounds", "Rowbottom", "Rowe", "Rowland", "Rowntree", "Royce",
              "Royceston", "Roydon", "Royle", "Royston", "Ruggles", "Rupertson",
              "Ryder", "Ryeley", "Ryely", "Ryer", "Ryers", "Ryley", "Sackville",
              "Sadler", "Salomon", "Salvage", "Sampson", "Samson", 
              "Samuels", "Samuelson", "Sanders", "Sanderson", "Sandford",
              "Sappington", "Sargent", "Saunders", "Sauvage", "Savage",
              "Savege", "Savidge", "Sawyer", "Saylor", "School", "Scott",
              "Scriven", "Scrivener", "Scrivenor", "Scrivens", "Seabrooke",
              "Seaver", "Sempers", "Senior", "Sergeant", "Sessions", "Sexton",
              "Shakesheave", "Sharman", "Sharrow", "Shelby", "Shepard",
              "Sherburne", "Simmons", "Simms", "Simon", "Simons", "Simonson",
              "Simpkin", "Simpson", "Sims", "Skinner", "Slater", "Smalls",
              "Smith", "Smythe", "Snelling", "Snider", "Sniders", "Snyder",
              "Snyders", "Southers", "Southgate", "Sowards", "Spalding",
              "Spear", "Spearing", "Spears", "Speight", "Spence", "Spencer",
              "Spurling", "Stack", "Stacks", "Stafford", "Stainthorpe", "Stamp",
              "Stanton", "Stark", "Starr", "Statham", "Steed", "Steele",
              "Steffen", "Stenet", "Stephens", "Stephenson", "Stern",
              "Stevens", "Stevenson", "Stidolph", "St John", "Stoddard",
              "Strange", "Street", "Strickland", "Stringer", "Stroud",
              "Strudwick", "Studwick", "Styles", "Sudworth", "Suggitt",
              "Sumner", "Sutton", "Sweet", "Swindlehurst", "Symons", "Tailor",
              "Tanner", "Tash", "Tasker", "Tate", "Tatham", "Taylor",
              "Teel", "Tennison", "Tennyson", "Thacker", "Thatcher", "Thomas",
              "Thompsett", "Thompson", "Thomson", "Thorn", "Thorne",
              "Thorpe", "Thrussell", "Thwaite", "Timberlake", "Timothyson",
              "Tinker", "Tipton", "Tittensor", "Tobias", "Toft", "Tolbert",
              "Tollemache", "Toller", "Towner", "Townsend", "Tracy", "Traiylor",
              "Trask", "Traver", "Travers", "Traves", "Travis", "Traviss",
              "Traylor", "Treloar", "Trengove", "Trent", "Trevis", "Triggs",
              "Tucker", "Tuff", "Tuft", "Tupper", "Turnbull", "Turner",
              "Tyler", "Tyson", "Underhill", "Underwood", "Upton", "Vance",
              "Van Middlesworth", "Varley", "Varnham", "Vaughan", "Vaughn",
              "Verity", "Vernon", "Victor", "Victors", "Victorson", "Vipond",
              "Virgo", "Wakefield", "Walker", "Wallace", "Wallis", "Walmsley",
              "Warren", "Wash", "Washington", "Watkins", "Watson",
              "Way", "Weaver", "Webster", "Weekes", "Wembley", "Wescott",
              "Westbrook", "Wheeler", "Wheelock", "Whinery", "Whitaker",
              "White", "Whitney", "Whittemore", "Whittle", "Wickham", "Wilcox",
              "Wilkerson", "Wilkins", "Wilkinson", "William", "Williams",
              "Williamson", "Willis", "Willoughby", "Wilson", "Winchester",
              "Winfield", "Winship", "Winston", "Winter", "Winterbottom",
              "Winthrop", "Witherspoon", "Wolf", "Wolfe", "Womack", "Wood",
              "Woodcock", "Woodham", "Woodhams", "Woods", "Woodward",
              "Wootton", "Wortham", "Wragge", "Wray", "Wyatt", "Wyght",
              "Wyndham", "Yap", "Yates", "Yong", "York", "Young", "Younge",
              "Yoxall", ]

StreetTypes = [ "Street", "Avenue", "Parade", "Ave", "St", "Rd", "Road",
                "Highway", "Rd", "Ave", "St", ]

from random import choice, randint

def chooseName(gender='MF'):
    if len(gender) > 1:
        gender = choice(gender)
    if gender == 'M':
        firstName = choice(BoysNames)
    else:
        firstName = choice(GirlsNames)
    lastName = choice(LastNames)
    return firstName + " " + lastName


def chooseAddress():
    city = choice(LastNames)
    district = choice([choice(LastNames), choice(LastNames), ""])
    while district == city:
        district = choice(LastNames)
    streetName = choice(LastNames)
    while streetName == city or streetName == district:
        streetName = choice(LastNames)
    suffixes = [""]
    for suffix in ["ton", "ton", "town", " City", "ville", "land"]:
        if not city.endswith(suffix):
            suffixes.append(suffix)
    city += choice(suffixes)
    number = randint(1, 110)
    if number > 100:
        number = randint(100, 1010)
        if number > 1000:
            number = randint(1000, 3000)
    number2 = randint(1, 300)
    letter = choice(["", "", "", "", chr(ord('a') + randint(0, 25))])
    street = "%d%s %s %s" % (number, letter, streetName, choice(StreetTypes))
    if number2 < 50:
        street = "%d/%s" % (number2, street)
    return (street, district, city)


def main():
    print (chooseName())
    addr = chooseAddress()
    print (addr[0])
    print (addr[1])
    print (addr[2])

if __name__ == "__main__":
    main()
